import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'
import 'index.css' // Generated by tailwind

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
