import React from 'react'
import ReactDOM from 'react-dom'
import App from './app'
import 'index.css' // Generated by tailwind

import firebase from 'firebase/app'
import 'firebase/analytics'
import 'firebase/auth'
import 'firebase/database'

const firebaseConfig = {
  apiKey: 'AIzaSyDxxe0OgBsbX9nHJEMh4wEQY5pKPZqBlEc',
  authDomain: 'caro-go.firebaseapp.com',
  projectId: 'caro-go',
  storageBucket: 'caro-go.appspot.com',
  messagingSenderId: '927723351972',
  appId: '1:927723351972:web:39cc113227b482e92a9b31',
  measurementId: 'G-T3CRNHQVTL',
}

firebase.initializeApp(firebaseConfig)

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
